#!/bin/bash
#
# Блок меню
#
# 0   - нажата клавиша OK
# 1   - нажата клавиша CANCEL
# 2   - нажата клавиша HELP
# 3   - нажата клавиша EXTRA
# 255 - нажата клавиша ESC
#
OPTION=$(dialog --title "NetTest v0.01" --menu "Выберитие действие:" 15 60 4 \
"1" "Проверка пинга" \
"2" "Трассировка" \
"3" "Проверка DNS-записей"  \
"4" "Полная проверка" \
"5" "Информация о подключении" \
"6" "Дополнительная информация" 3>&1 1>&2 2>&3)
#
#Конец блока меню
#

exit=$?
if [ $exit = 1 ]; then
	dialog --title "Выход"  --msgbox "Всего доброго!" 10 40 #окно при выходе из скрипта
	clear #очистка экрана консоли
	exit
fi

case $OPTION in
	1)
	user_ping=$(dialog --title "Проверка пинга"  --inputbox "Введите доменное имя/ip-адрес:" 8 40 3>&1 1>&2 2>&3 3>&-) #Окно ввода адреса и помещение его в переменную
	#ping_exit=$?
	#if [ $ping_exit = 1 ]; then
        #	bash NetTest
	#fi


	value_ping=$(dialog --title "Проверка пинга"  --inputbox "Укажите количество хопов:" 8 40 3>&1 1>&2 2>&3 3>&-) #Окно ввода адреса и помещение его в переменную
	ping_inp=$(ping -c $value_ping $user_ping &) #помещение вывода программы в переменную
	{
                for ((i = 0 ; i <= 100 ; i+=50)); do
                sleep 1
                echo $i
                done
        } | dialog --title "$user_ping"  --gauge "Ожидайте сбора данных..." 6 60 0 #окно ожидания
	dialog --title "$user_ping"  --msgbox "$ping_inp" 40 70 # Вывод команды в окне
	bash NetTest #Возврат в основной скрипт
	;;

	2)
	user_tr=$(dialog --title "Трассировка" --inputbox "Введите доменное имя/ip-адрес:" 8 40 3>&1 1>&2 2>&3 3>&-)
	value_ping=$(dialog --title "Трассировка"  --inputbox "Укажите количество хопов:" 8 40 3>&1 1>&2 2>&3 3>&-) #Окно ввода адреса и помещение его в переменную
        tr_inp=$(traceroute $user_tr &) 
	{
		for ((i = 0 ; i <= 100 ; i+=50)); do
        	sleep 1
        	echo $i
    		done
	} | dialog --title "$user_tr" --gauge "Ожидайте сбора данных" 6 60 0
	dialog --title "$user_tr"  --msgbox "$tr_inp" 40 70
	bash NetTest
	;;

	3)
	DNS_RECORD=$(dialog  --checklist "Выберитие запись:" 20 60 10 \
	"А" "A" off \
	"АААA" "AAA" off \
	"MX" "MX" off \
	"PTR" "PTR" off \
	"TXT" "TXT" off \
	"SOA" "SOA" off \
	"NS" "NS" off \
	"CNAME" "CNAME" off \
	"CAA" "CAA" off \
	"SRV" "SRV" off 3>&1 1>&2 2>&3)
	
	echo "$DNS_RECORD"
	
	#dialog --title   --msgbox  40 70
	;;

	4)
	user_input_full=$(dialog --inputbox "Введите доменное имя/ip-адрес:" 8 40 3>&1 1>&2 2>&3 3>&-)

	;;

	5)
	CONF_OPTION=$(dialog --title "Информация о подключении" --menu "Выберитие действие:" 15 60 4 \
	"1" "Конфигурация подключения" \
	"2" "Внешний ip" \
	"3" "Network_Manager-tui"  3>&1 1>&2 2>&3)

	esc=$?
		if [ $esc = 1 ]; then
			bash NetTest
		else
			echo ""
		fi


		case $CONF_OPTION in
			1)
			;;
			2)
			ip_out=$(curl curlmyip.ru 2>&1 | egrep "([0-9]{1,3}\.){3}" )
			dialog --title "Внешний ip-адрес"  --msgbox "$ip_out" 15 30
			bash NetTest
			;;
			3)
			nmtui
			;;
		esac
	;;

	6)
	DOP_OPTION=$(dialog --title "ДОполнительная информация" --menu "Выберитие действие:" 15 60 4 \
        "1" "Версия" \
        "2" "Информация" \
        "3" "Печеньки"  3>&1 1>&2 2>&3)

	;;
esac


